version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1c38d12njua73"
s3_prefix = "test3"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"first\""
