AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Announcement

  Sample SAM Template for Announcement

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  AnnouncementsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "AnnouncementsTopic"
      TopicName: "AnnouncementsTopic"

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: "sudhakartestaws@gmail.com"
      Protocol: email
      TopicArn: !Ref AnnouncementsTopic

  AnnouncementsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Announcements
      AttributeDefinitions:
      - AttributeName: "title"
        AttributeType: "S"

      KeySchema:
      - AttributeName: "title"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.app1
      Runtime: python3.7
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref AnnouncementsTable
        - SNSPublishMessagePolicy:
            TopicName: "AnnouncementsTopic"


      Events:
        PostAnnouncements:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /announcements
            Method: post
        ListAnnouncements:
          Type: Api
          Properties:
            Path: /announcements
            Method: get
        test:
          Type: Api
          Properties:
            Path: /test
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
